// Weatherguessr - US States Weather Data
// Real weather statistics for all 50 US states

const weatherData = {
    // Tornado frequency (average annual tornadoes per state)
    tornados: {
        "Texas": 155,
        "Kansas": 96,
        "Florida": 66,
        "Oklahoma": 62,
        "Nebraska": 57,
        "Illinois": 54,
        "Colorado": 53,
        "Iowa": 51,
        "Minnesota": 45,
        "Missouri": 45,
        "Alabama": 44,
        "Mississippi": 43,
        "Arkansas": 39,
        "Louisiana": 37,
        "Tennessee": 32,
        "Indiana": 22,
        "Kentucky": 21,
        "Ohio": 19,
        "Georgia": 18,
        "South Dakota": 18,
        "North Dakota": 17,
        "Michigan": 16,
        "Wisconsin": 16,
        "Pennsylvania": 15,
        "South Carolina": 15,
        "North Carolina": 14,
        "Virginia": 13,
        "New York": 10,
        "Maryland": 9,
        "West Virginia": 8,
        "New Jersey": 7,
        "Connecticut": 6,
        "Massachusetts": 6,
        "Delaware": 5,
        "Vermont": 4,
        "New Hampshire": 4,
        "Maine": 3,
        "Rhode Island": 2,
        "California": 11,
        "Oregon": 3,
        "Washington": 2,
        "Idaho": 3,
        "Montana": 4,
        "Wyoming": 3,
        "Nevada": 2,
        "Utah": 2,
        "Arizona": 4,
        "New Mexico": 3,
        "Alaska": 0,
        "Hawaii": 1
    },

    // Annual rainfall (inches per year)
    rainfall: {
        "Hawaii": 63.7,
        "Louisiana": 60.1,
        "Mississippi": 59.0,
        "Alabama": 58.3,
        "Florida": 54.5,
        "Tennessee": 54.2,
        "Georgia": 50.7,
        "Arkansas": 50.6,
        "South Carolina": 49.8,
        "North Carolina": 50.3,
        "Kentucky": 48.9,
        "Virginia": 44.3,
        "West Virginia": 45.2,
        "Indiana": 41.7,
        "Ohio": 39.1,
        "Missouri": 42.2,
        "Illinois": 39.2,
        "Iowa": 34.0,
        "Minnesota": 27.6,
        "Wisconsin": 32.6,
        "Michigan": 32.8,
        "Pennsylvania": 42.9,
        "New York": 41.8,
        "New Jersey": 47.1,
        "Connecticut": 50.3,
        "Rhode Island": 47.9,
        "Massachusetts": 47.7,
        "Vermont": 42.7,
        "New Hampshire": 43.4,
        "Maine": 42.2,
        "Delaware": 45.7,
        "Maryland": 44.5,
        "Texas": 28.9,
        "Oklahoma": 36.5,
        "Kansas": 28.9,
        "Nebraska": 23.6,
        "South Dakota": 20.1,
        "North Dakota": 17.8,
        "Montana": 15.3,
        "Wyoming": 12.9,
        "Colorado": 17.1,
        "New Mexico": 14.6,
        "Arizona": 12.6,
        "Utah": 12.2,
        "Nevada": 9.5,
        "Idaho": 18.9,
        "Washington": 38.4,
        "Oregon": 27.4,
        "California": 22.4,
        "Alaska": 22.5
    },

    // Highest recorded temperature (Fahrenheit)
    highestTemp: {
        "California": 134,
        "Arizona": 128,
        "Nevada": 125,
        "New Mexico": 122,
        "Texas": 120,
        "Oklahoma": 120,
        "Kansas": 121,
        "Arkansas": 120,
        "Missouri": 118,
        "Illinois": 117,
        "Indiana": 116,
        "Ohio": 113,
        "Kentucky": 114,
        "Tennessee": 113,
        "Mississippi": 115,
        "Alabama": 112,
        "Georgia": 112,
        "Florida": 109,
        "South Carolina": 111,
        "North Carolina": 110,
        "Virginia": 110,
        "West Virginia": 112,
        "Maryland": 109,
        "Delaware": 110,
        "New Jersey": 110,
        "Pennsylvania": 111,
        "New York": 108,
        "Connecticut": 106,
        "Rhode Island": 104,
        "Massachusetts": 107,
        "Vermont": 105,
        "New Hampshire": 106,
        "Maine": 105,
        "Michigan": 112,
        "Wisconsin": 114,
        "Minnesota": 115,
        "Iowa": 118,
        "Nebraska": 118,
        "South Dakota": 120,
        "North Dakota": 121,
        "Montana": 117,
        "Wyoming": 115,
        "Colorado": 115,
        "Utah": 117,
        "Idaho": 118,
        "Washington": 118,
        "Oregon": 119,
        "Alaska": 100,
        "Hawaii": 100
    },

    // Lowest recorded temperature (Fahrenheit) - Lower (more negative) values rank higher
    lowestTemp: {
        "Alaska": -80,
        "Montana": -70,
        "North Dakota": -60,
        "Minnesota": -60,
        "Wyoming": -66,
        "Maine": -50,
        "Vermont": -50,
        "New Hampshire": -50,
        "Wisconsin": -55,
        "Michigan": -51,
        "New York": -52,
        "Idaho": -60,
        "Colorado": -61,
        "Utah": -69,
        "South Dakota": -58,
        "Nebraska": -47,
        "Iowa": -47,
        "Illinois": -36,
        "Indiana": -36,
        "Ohio": -39,
        "Pennsylvania": -42,
        "West Virginia": -37,
        "Virginia": -30,
        "Maryland": -40,
        "Delaware": -17,
        "New Jersey": -34,
        "Connecticut": -32,
        "Rhode Island": -25,
        "Massachusetts": -35,
        "Washington": -48,
        "Oregon": -54,
        "Nevada": -50,
        "California": -45,
        "Arizona": -40,
        "New Mexico": -50,
        "Texas": -23,
        "Oklahoma": -27,
        "Kansas": -40,
        "Missouri": -40,
        "Arkansas": -29,
        "Tennessee": -32,
        "Kentucky": -37,
        "Mississippi": -19,
        "Alabama": -27,
        "Georgia": -17,
        "Florida": -2,
        "South Carolina": -19,
        "North Carolina": -34,
        "Louisiana": -16,
        "Hawaii": 12
    },

    // Annual sunshine hours
    sunshine: {
        "Arizona": 4012,
        "New Mexico": 3415,
        "Nevada": 3825,
        "Texas": 2640,
        "California": 3055,
        "Colorado": 3007,
        "Utah": 3029,
        "Wyoming": 2971,
        "Montana": 2747,
        "Idaho": 2750,
        "Oregon": 2341,
        "Washington": 2170,
        "Alaska": 2061,
        "Hawaii": 2714,
        "Florida": 2333,
        "Louisiana": 2160,
        "Mississippi": 2160,
        "Alabama": 2160,
        "Georgia": 2160,
        "South Carolina": 2160,
        "North Carolina": 2139,
        "Tennessee": 2074,
        "Kentucky": 2074,
        "Virginia": 2074,
        "West Virginia": 2074,
        "Maryland": 2074,
        "Delaware": 2074,
        "New Jersey": 2074,
        "Pennsylvania": 2074,
        "New York": 2074,
        "Connecticut": 2074,
        "Rhode Island": 2074,
        "Massachusetts": 2074,
        "Vermont": 2074,
        "New Hampshire": 2074,
        "Maine": 2074,
        "Michigan": 2074,
        "Wisconsin": 2074,
        "Minnesota": 2074,
        "Iowa": 2074,
        "Illinois": 2074,
        "Indiana": 2074,
        "Ohio": 2074,
        "Missouri": 2074,
        "Arkansas": 2074,
        "Oklahoma": 2074,
        "Kansas": 2074,
        "Nebraska": 2074,
        "South Dakota": 2074,
        "North Dakota": 2074
    },

    // Average wind speed (mph)
    wind: {
        "Wyoming": 21.5,
        "South Dakota": 20.2,
        "Montana": 19.9,
        "North Dakota": 19.8,
        "Nebraska": 18.5,
        "Kansas": 18.0,
        "Oklahoma": 17.5,
        "Texas": 16.8,
        "Colorado": 16.5,
        "New Mexico": 16.0,
        "Arizona": 15.5,
        "Utah": 15.0,
        "Nevada": 14.5,
        "Idaho": 14.0,
        "Washington": 13.5,
        "Oregon": 13.0,
        "California": 12.5,
        "Alaska": 12.0,
        "Hawaii": 11.5,
        "Minnesota": 11.0,
        "Iowa": 10.5,
        "Wisconsin": 10.0,
        "Michigan": 9.5,
        "Illinois": 9.0,
        "Indiana": 8.5,
        "Ohio": 8.0,
        "Missouri": 7.5,
        "Arkansas": 7.0,
        "Kentucky": 6.5,
        "Tennessee": 6.0,
        "Mississippi": 5.5,
        "Alabama": 5.0,
        "Georgia": 4.5,
        "Florida": 4.0,
        "South Carolina": 3.5,
        "North Carolina": 3.0,
        "Virginia": 2.5,
        "West Virginia": 2.0,
        "Maryland": 1.5,
        "Delaware": 1.0,
        "New Jersey": 0.5,
        "Pennsylvania": 0.0,
        "New York": -0.5,
        "Connecticut": -1.0,
        "Rhode Island": -1.5,
        "Massachusetts": -2.0,
        "Vermont": -2.5,
        "New Hampshire": -3.0,
        "Maine": -3.5
    },

    // Annual snowfall (inches)
    snowfall: {
        "Alaska": 64.5,
        "Vermont": 89.3,
        "Maine": 77.3,
        "New Hampshire": 71.4,
        "New York": 61.7,
        "Michigan": 60.7,
        "Wisconsin": 47.7,
        "Minnesota": 45.6,
        "Massachusetts": 43.8,
        "Connecticut": 37.6,
        "Rhode Island": 35.9,
        "Pennsylvania": 33.4,
        "Ohio": 28.0,
        "Indiana": 25.9,
        "Illinois": 25.8,
        "Iowa": 30.2,
        "Missouri": 13.4,
        "Kansas": 15.6,
        "Nebraska": 27.8,
        "South Dakota": 38.1,
        "North Dakota": 39.8,
        "Montana": 25.7,
        "Wyoming": 77.8,
        "Colorado": 67.3,
        "Utah": 42.6,
        "Idaho": 18.7,
        "Washington": 17.4,
        "Oregon": 13.9,
        "Nevada": 21.9,
        "California": 2.3,
        "Arizona": 0.3,
        "New Mexico": 9.6,
        "Texas": 0.1,
        "Oklahoma": 5.8,
        "Arkansas": 4.0,
        "Louisiana": 0.2,
        "Mississippi": 0.4,
        "Alabama": 0.6,
        "Georgia": 0.7,
        "Florida": 0.0,
        "South Carolina": 1.0,
        "North Carolina": 3.7,
        "Tennessee": 4.8,
        "Kentucky": 10.9,
        "West Virginia": 33.2,
        "Virginia": 10.2,
        "Maryland": 20.1,
        "Delaware": 15.0,
        "New Jersey": 23.1,
        "Hawaii": 0.0
    },

    // Lightning strike frequency (strikes per square mile per year)
    lightning: {
        "Florida": 83.2,
        "Louisiana": 67.5,
        "Mississippi": 52.3,
        "Alabama": 47.3,
        "Arkansas": 43.2,
        "Georgia": 41.7,
        "South Carolina": 40.6,
        "Oklahoma": 38.7,
        "Missouri": 35.1,
        "Illinois": 32.1,
        "Indiana": 30.2,
        "Kentucky": 28.9,
        "Tennessee": 27.8,
        "Texas": 26.4,
        "Kansas": 24.7,
        "Iowa": 23.1,
        "Nebraska": 21.8,
        "Minnesota": 20.5,
        "Wisconsin": 19.2,
        "Michigan": 18.1,
        "Ohio": 17.3,
        "Pennsylvania": 16.7,
        "New York": 15.9,
        "West Virginia": 15.2,
        "Virginia": 14.6,
        "North Carolina": 13.9,
        "Maryland": 13.2,
        "Delaware": 12.5,
        "New Jersey": 11.8,
        "Connecticut": 11.1,
        "Rhode Island": 10.4,
        "Massachusetts": 9.7,
        "Vermont": 9.0,
        "New Hampshire": 8.3,
        "Maine": 7.6,
        "Colorado": 6.9,
        "New Mexico": 6.2,
        "Arizona": 5.5,
        "Utah": 4.8,
        "Nevada": 4.1,
        "California": 3.4,
        "Oregon": 2.7,
        "Washington": 2.0,
        "Idaho": 1.3,
        "Montana": 0.6,
        "Wyoming": 0.0,
        "North Dakota": -0.6,
        "South Dakota": -1.2,
        "Alaska": -1.8,
        "Hawaii": -2.4
    }
};

// State flags/emojis
const stateFlags = {
    "Alabama": "🏴‍☠️", "Alaska": "🏔️", "Arizona": "🌵", "Arkansas": "💎", "California": "🌴",
    "Colorado": "🏔️", "Connecticut": "🌳", "Delaware": "🦀", "Florida": "🌴", "Georgia": "🍑",
    "Hawaii": "🌺", "Idaho": "🥔", "Illinois": "🌽", "Indiana": "🏀", "Iowa": "🌽",
    "Kansas": "🌻", "Kentucky": "🐎", "Louisiana": "🎭", "Maine": "🦞", "Maryland": "🦀",
    "Massachusetts": "🦃", "Michigan": "🍒", "Minnesota": "🦆", "Mississippi": "🌊", "Missouri": "🎸",
    "Montana": "🏔️", "Nebraska": "🌽", "Nevada": "🎰", "New Hampshire": "🍁", "New Jersey": "🌊",
    "New Mexico": "🌶️", "New York": "🗽", "North Carolina": "🐗", "North Dakota": "🌻", "Ohio": "🌰",
    "Oklahoma": "🌾", "Oregon": "🌲", "Pennsylvania": "🔔", "Rhode Island": "🦞", "South Carolina": "🌴",
    "South Dakota": "🏔️", "Tennessee": "🎸", "Texas": "🤠", "Utah": "🏔️", "Vermont": "🍁",
    "Virginia": "🌊", "Washington": "🌲", "West Virginia": "🏔️", "Wisconsin": "🧀", "Wyoming": "🐂"
};

// Helper function to get rankings for a category
function getRankings(category) {
    const data = weatherData[category];
    
    // For lowest temperature, we want the lowest (most negative) value to rank #1
    // For all other categories, we want the highest value to rank #1
    const sortOrder = category === 'lowestTemp' ? (a, b) => a[1] - b[1] : (a, b) => b[1] - a[1];
    const sorted = Object.entries(data).sort(sortOrder);
    
    const rankings = {};
    sorted.forEach((entry, index) => {
        rankings[entry[0]] = index + 1;
    });
    
    return rankings;
}

// Get all rankings for all categories
const rankings = {};
Object.keys(weatherData).forEach(category => {
    rankings[category] = getRankings(category);
});

// Export data for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { weatherData, stateFlags, rankings };
}
